import './globals.css';
import { Providers } from '@/components/global/providers';
import type { Metadata } from 'next';
import  {ReactNode, Suspense} from 'react';
import Loading from './loading';

export const metadata: Metadata = {
  title: 'Tunify',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang='en'>
      <Suspense fallback={<Loading />}>
        <body>
          <Providers>{children}</Providers>
        </body>
      </Suspense>
    </html>
  );
}
